/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author Abigail
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        lblLogo.setIcon(new ImageIcon("Images/Logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        FlightMenu = new javax.swing.JMenu();
        CreateFlightMenu = new javax.swing.JMenuItem();
        ViewFlightMenu = new javax.swing.JMenuItem();
        EditFlightMenu = new javax.swing.JMenuItem();
        DelFlightMenu = new javax.swing.JMenuItem();
        PilotMenu = new javax.swing.JMenu();
        CreatePilotMenu = new javax.swing.JMenuItem();
        ViewPilotMenu = new javax.swing.JMenuItem();
        EditPilotMenu = new javax.swing.JMenuItem();
        DelPilotMenu = new javax.swing.JMenuItem();
        AircraftsMenu = new javax.swing.JMenu();
        CreateAircraftMenu = new javax.swing.JMenuItem();
        ViewAircraftMenu = new javax.swing.JMenuItem();
        EditAircraftMenu = new javax.swing.JMenuItem();
        DelAircraftMenu = new javax.swing.JMenuItem();
        AirportMenu = new javax.swing.JMenu();
        CreateAirportMenu = new javax.swing.JMenuItem();
        DelAirportMenu1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 204));
        lblTitle.setText("AlphaFlights");

        jMenu1.setText("File");

        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Search");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        FlightMenu.setText("Flights");

        CreateFlightMenu.setText("Create Flight");
        CreateFlightMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFlightMenuActionPerformed(evt);
            }
        });
        FlightMenu.add(CreateFlightMenu);

        ViewFlightMenu.setText("View Flight");
        ViewFlightMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFlightMenuActionPerformed(evt);
            }
        });
        FlightMenu.add(ViewFlightMenu);

        EditFlightMenu.setText("Edit Flight");
        EditFlightMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFlightMenuActionPerformed(evt);
            }
        });
        FlightMenu.add(EditFlightMenu);

        DelFlightMenu.setText("Delete Flight");
        DelFlightMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelFlightMenuActionPerformed(evt);
            }
        });
        FlightMenu.add(DelFlightMenu);

        jMenu2.add(FlightMenu);

        PilotMenu.setText("Pilots");

        CreatePilotMenu.setText("Create Pilot");
        CreatePilotMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePilotMenuActionPerformed(evt);
            }
        });
        PilotMenu.add(CreatePilotMenu);

        ViewPilotMenu.setText("View Pilot");
        ViewPilotMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPilotMenuActionPerformed(evt);
            }
        });
        PilotMenu.add(ViewPilotMenu);

        EditPilotMenu.setText("Edit Pilot");
        EditPilotMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPilotMenuActionPerformed(evt);
            }
        });
        PilotMenu.add(EditPilotMenu);

        DelPilotMenu.setText("Delete Pilot");
        DelPilotMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelPilotMenuActionPerformed(evt);
            }
        });
        PilotMenu.add(DelPilotMenu);

        jMenu2.add(PilotMenu);

        AircraftsMenu.setText("Aircrafts");

        CreateAircraftMenu.setText("Create Aircraft");
        CreateAircraftMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAircraftMenuActionPerformed(evt);
            }
        });
        AircraftsMenu.add(CreateAircraftMenu);

        ViewAircraftMenu.setText("View Aircraft");
        ViewAircraftMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAircraftMenuActionPerformed(evt);
            }
        });
        AircraftsMenu.add(ViewAircraftMenu);

        EditAircraftMenu.setText("Edit Aircraft");
        EditAircraftMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAircraftMenuActionPerformed(evt);
            }
        });
        AircraftsMenu.add(EditAircraftMenu);

        DelAircraftMenu.setText("Delete Aircraft");
        DelAircraftMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelAircraftMenuActionPerformed(evt);
            }
        });
        AircraftsMenu.add(DelAircraftMenu);

        jMenu2.add(AircraftsMenu);

        AirportMenu.setText("Airports");

        CreateAirportMenu.setText("Create Airport");
        CreateAirportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAirportMenuActionPerformed(evt);
            }
        });
        AirportMenu.add(CreateAirportMenu);

        DelAirportMenu1.setText("Delete Airport");
        DelAirportMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelAirportMenu1ActionPerformed(evt);
            }
        });
        AirportMenu.add(DelAirportMenu1);

        jMenu2.add(AirportMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 275, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditFlightMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFlightMenuActionPerformed
        // TODO add your handling code here:
        new EditFlight().setVisible(true);
    }//GEN-LAST:event_EditFlightMenuActionPerformed

    private void EditPilotMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPilotMenuActionPerformed
        // TODO add your handling code here:
        new EditPilots().setVisible(true);
    }//GEN-LAST:event_EditPilotMenuActionPerformed

    private void EditAircraftMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAircraftMenuActionPerformed
        // TODO add your handling code here:
        new EditAircrafts().setVisible(true);
    }//GEN-LAST:event_EditAircraftMenuActionPerformed

    private void CreateFlightMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFlightMenuActionPerformed
        // TODO add your handling code here:
        new CreateFlight().setVisible(true);
    }//GEN-LAST:event_CreateFlightMenuActionPerformed

    private void ViewFlightMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFlightMenuActionPerformed
        // TODO add your handling code here:
        new ViewFlight().setVisible(true);
    }//GEN-LAST:event_ViewFlightMenuActionPerformed

    private void DelFlightMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelFlightMenuActionPerformed
        // TODO add your handling code here:
        new DeleteFlight().setVisible(true);
    }//GEN-LAST:event_DelFlightMenuActionPerformed

    private void CreatePilotMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePilotMenuActionPerformed
        // TODO add your handling code here:
        new CreatePilots().setVisible(true);
    }//GEN-LAST:event_CreatePilotMenuActionPerformed

    private void DelPilotMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelPilotMenuActionPerformed
        // TODO add your handling code here:
        new DeletePilots().setVisible(true);
    }//GEN-LAST:event_DelPilotMenuActionPerformed

    private void CreateAircraftMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAircraftMenuActionPerformed
        // TODO add your handling code here:
        new CreateAircrafts().setVisible(true);
    }//GEN-LAST:event_CreateAircraftMenuActionPerformed

    private void DelAircraftMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelAircraftMenuActionPerformed
        // TODO add your handling code here:
        new DeleteAircrafts().setVisible(true);
    }//GEN-LAST:event_DelAircraftMenuActionPerformed

    private void CreateAirportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAirportMenuActionPerformed
        // TODO add your handling code here:
       new CreateAirport().setVisible(true);
    }//GEN-LAST:event_CreateAirportMenuActionPerformed

    private void DelAirportMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelAirportMenu1ActionPerformed
        // TODO add your handling code here:
        new DeleteAirports().setVisible(true);
    }//GEN-LAST:event_DelAirportMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new ViewPassengers().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new help().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void ViewAircraftMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAircraftMenuActionPerformed
        // TODO add your handling code here:
        new ViewAircrafts().setVisible(true);
    }//GEN-LAST:event_ViewAircraftMenuActionPerformed

    private void ViewPilotMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPilotMenuActionPerformed
        // TODO add your handling code here:
        new ViewPilots().setVisible(true);
    }//GEN-LAST:event_ViewPilotMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AircraftsMenu;
    private javax.swing.JMenu AirportMenu;
    private javax.swing.JMenuItem CreateAircraftMenu;
    private javax.swing.JMenuItem CreateAirportMenu;
    private javax.swing.JMenuItem CreateFlightMenu;
    private javax.swing.JMenuItem CreatePilotMenu;
    private javax.swing.JMenuItem DelAircraftMenu;
    private javax.swing.JMenuItem DelAirportMenu1;
    private javax.swing.JMenuItem DelFlightMenu;
    private javax.swing.JMenuItem DelPilotMenu;
    private javax.swing.JMenuItem EditAircraftMenu;
    private javax.swing.JMenuItem EditFlightMenu;
    private javax.swing.JMenuItem EditPilotMenu;
    private javax.swing.JMenu FlightMenu;
    private javax.swing.JMenu PilotMenu;
    private javax.swing.JMenuItem ViewAircraftMenu;
    private javax.swing.JMenuItem ViewFlightMenu;
    private javax.swing.JMenuItem ViewPilotMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
