
import java.text.SimpleDateFormat;
import java.time.YearMonth;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abigail
 */
public class EditPilots extends javax.swing.JFrame {
    
    public int year = GregorianCalendar.getInstance().get(GregorianCalendar.YEAR) - 18;
    public int yearMargin  = GregorianCalendar.getInstance().get(GregorianCalendar.YEAR) - 70;

    public static GregorianCalendar cl;
    public static String fdt;
    

    /**
     * Creates new form EditPilots
     */
    public EditPilots() {
        initComponents();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        CrudOperations.FillCmbs("SELECT IDCardNumber FROM pilot_tbl", cmbPilots);
        
        for(int i = year; i > yearMargin; i--){
            System.out.println(i);
            cmbYears.addItem(Integer.toString(i));
        }
        
        updateDay();
        FillDetails();
    }
    
    public void FillDetails(){
        CrudOperations.SetSelectedItem("SELECT YEAR(Dob) FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", cmbYears);
        CrudOperations.SetSelectedItem("SELECT MONTHNAME(Dob) FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", cmbMonths);
        CrudOperations.SetSelectedItem("SELECT DAY(Dob) FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", cmbDays);
        CrudOperations.ViewDetailsTxt("SELECT PilotName FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", txtName);
        CrudOperations.ViewDetailsTxt("SELECT PilotSurname FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", txtSurname);
        CrudOperations.ViewDetailsTxt("SELECT ContactNo1 FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", txtContactNumber1);
        CrudOperations.ViewDetailsTxt("SELECT ContactNo2 FROM Pilot_tbl WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'", txtContactNumber2);
    }
    
    public void updateDay(){
        cmbDays.removeAllItems();

        int userYear = Integer.parseInt((String)cmbYears.getSelectedItem());
        YearMonth selectedMonth = YearMonth.of(userYear, cmbMonths.getSelectedIndex() + 1);
        for(int i = 0; i < selectedMonth.lengthOfMonth(); i++){
            cmbDays.addItem(Integer.toString(i + 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPilots = new javax.swing.JLabel();
        cmbPilots = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblContactNumber1 = new javax.swing.JLabel();
        lblContactNumber2 = new javax.swing.JLabel();
        txtContactNumber2 = new javax.swing.JTextField();
        txtContactNumber1 = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        cmbYears = new javax.swing.JComboBox<>();
        lblMonth = new javax.swing.JLabel();
        cmbMonths = new javax.swing.JComboBox<>();
        lblDay = new javax.swing.JLabel();
        cmbDays = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPilots.setText("Pilot ID Card Number");

        cmbPilots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilotsActionPerformed(evt);
            }
        });

        lblName.setText("First Name");

        lblSurname.setText("Last Name");

        lblContactNumber1.setText("Contact Number (1)");

        lblContactNumber2.setText("Contact Number (2)");

        lblDob.setText("Date Of Birth:");

        lblYear.setText("Year");

        cmbYears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearsActionPerformed(evt);
            }
        });

        lblMonth.setText("Month");

        cmbMonths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthsActionPerformed(evt);
            }
        });

        lblDay.setText("Day");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPilots)
                            .addComponent(lblName)
                            .addComponent(lblSurname)
                            .addComponent(lblContactNumber1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMonth))
                                .addComponent(lblContactNumber2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContactNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPilots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDay)))))
                    .addComponent(lblDob)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cmbMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPilots)
                    .addComponent(cmbPilots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSurname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNumber1)
                    .addComponent(txtContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNumber2)
                    .addComponent(txtContactNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblDob)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(lblMonth)
                    .addComponent(lblDay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbYearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearsActionPerformed
        // TODO add your handling code here:
        updateDay();
    }//GEN-LAST:event_cmbYearsActionPerformed

    private void cmbMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthsActionPerformed
        // TODO add your handling code here:
        updateDay();
    }//GEN-LAST:event_cmbMonthsActionPerformed

    private void cmbPilotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilotsActionPerformed
        // TODO add your handling code here:
        for(int i = year; i > yearMargin; i--){
            System.out.println(i);
            cmbYears.addItem(Integer.toString(i));
        }
        updateDay();
        FillDetails();
    }//GEN-LAST:event_cmbPilotsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        int yr = (int) Integer.parseInt(cmbYears.getSelectedItem().toString());
        int month = cmbMonths.getSelectedIndex();
        int day = (int) Integer.parseInt(cmbDays.getSelectedItem().toString());
        
        cl = new GregorianCalendar(yr, month, day);
        fdt = df.format(cl.getTime());
        
        CrudOperations.Validation(txtName, "NoDigit");
        boolean NameContains = CrudOperations.Validation(txtName, "NoDigit");
        
        CrudOperations.Validation(txtSurname, "NoDigit");
        boolean SurnameContains = CrudOperations.Validation(txtSurname, "NoDigit");
        
        CrudOperations.Validation(txtContactNumber1, "NoString");
        boolean ContNo1Contains = CrudOperations.Validation(txtContactNumber1, "NoString");
        
        CrudOperations.Validation(txtContactNumber2, "NoStringEmptyY");
        boolean ContNo2Contains = CrudOperations.Validation(txtContactNumber2, "NoStringEmptyY");
        
        if(NameContains == false && SurnameContains == false && ContNo1Contains == false && ContNo2Contains == false){
            CrudOperations.EditDetails("UPDATE Pilot_tbl SET PilotName = '" + txtName.getText() +
                    "', PilotSurname = '" + txtSurname.getText() +
                    "', Dob = '" + fdt +
                    "', ContactNo1 = '" + txtContactNumber1.getText() +
                    "', ContactNo2 = '" + txtContactNumber2.getText() + "' WHERE IDCardNumber = '" + cmbPilots.getSelectedItem() + "'");

            JOptionPane.showMessageDialog(null, "Pilot Details Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPilots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPilots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPilots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPilots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPilots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDays;
    private javax.swing.JComboBox<String> cmbMonths;
    private javax.swing.JComboBox<String> cmbPilots;
    private javax.swing.JComboBox<String> cmbYears;
    private javax.swing.JLabel lblContactNumber1;
    private javax.swing.JLabel lblContactNumber2;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPilots;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtContactNumber1;
    private javax.swing.JTextField txtContactNumber2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
