/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Abigail
 */
public class ViewFlight extends javax.swing.JFrame {

    /**
     * Creates new form ViewFlight
     */
    public ViewFlight() {
        initComponents();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        FillFlights();
    }
    
    public void FillFlights(){
        DbConnection.conn();
        Connection conn = DbConnection.conn;
        try{
            Statement st = conn.createStatement();
            
            String query = "SELECT FlightNo FROM flights_tbl";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                cmbFlights.addItem(rs.getString(1));
            }
        }
        catch (SQLException ex) {
            System.out.println("ERROR: " + ex);
        }

    }
    
    public void queryFill(String qry, JLabel lbl){
        DbConnection.conn();
        Connection conn = DbConnection.conn;
        try{
            Statement st = conn.createStatement();
            
            String query = qry;
            ResultSet rs = st.executeQuery(query);
            
            lbl.setText("");
            while(rs.next()){
                lbl.setText(rs.getString(1));
            }
        }
        catch (SQLException ex) {
            System.out.println("ERROR: " + ex);
        }
    }
    
    public void GetDetails(){
        queryFill("SELECT NoOfCrew FROM flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'" , lblCrew);
        queryFill("SELECT AircraftName FROM Aircraft_tbl WHERE AircraftId IN (SELECT AircraftId FROM Flights_tbl)", lblAircraft);
        queryFill("SELECT AirportName FROM Airport_tbl WHERE AirportId IN (SELECT AirportDep FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "')", lblDepAirport);
        queryFill("SELECT CityName from city_tbl WHERE CityId IN (SELECT CityId FROM Airport_tbl WHERE AirportName = '" + lblDepAirport.getText() + "')", lblDepCity);
        queryFill("SELECT CityName from city_tbl WHERE CityId IN (SELECT CityId FROM Airport_tbl WHERE AirportName = '" + lblDepAirport.getText() + "')", lblDepCity);
        queryFill("SELECT CountryName FROM country_tbl WHERE CountryId IN (SELECT CountryId FROM City_tbl WHERE CityName = '" + lblDepCity.getText() + "')", lblDepCountry);
        queryFill("SELECT AirportName FROM Airport_tbl WHERE AirportId IN (SELECT AirportDest FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "')", lblDestAirport);
        queryFill("SELECT CityName from city_tbl WHERE CityId IN (SELECT CityId FROM Airport_tbl WHERE AirportName = '" + lblDestAirport.getText() + "')", lblDestCity);
        queryFill("SELECT CountryName FROM country_tbl WHERE CountryId IN (SELECT CountryId FROM City_tbl WHERE CityName = '" + lblDestCity.getText() + "')", lblDestCountry);
        queryFill("SELECT Duration FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'", lblDuration);
        queryFill("SELECT TimeFrom FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'", lblTimeFrom);
        queryFill("SELECT TimeTo FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'", lblTimeTo);
        queryFill("SELECT FlightDate FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'", lblDate);
        queryFill("SELECT Price FROM Flights_tbl WHERE FlightNo = '" + cmbFlights.getSelectedItem() + "'", lblPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbFlights = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblAircraft = new javax.swing.JLabel();
        lblDepCountry = new javax.swing.JLabel();
        lblDestCountry = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTimeFrom = new javax.swing.JLabel();
        lblTimeTo = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDestCity = new javax.swing.JLabel();
        lblDestAirport = new javax.swing.JLabel();
        lblDepCity = new javax.swing.JLabel();
        lblDepAirport = new javax.swing.JLabel();
        lblCrew = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFlightsActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of Crew");

        jLabel2.setText("Aircraft");

        jLabel3.setText("Departure");

        jLabel4.setText("Destination");

        jLabel5.setText("Duration");

        jLabel6.setText("Date (yyyy-mm-dd)");

        jLabel7.setText("Time From");

        jLabel8.setText("Time To");

        jLabel9.setText("Price (Per Person)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(lblTimeTo)
                            .addComponent(lblTimeFrom)
                            .addComponent(lblDate)
                            .addComponent(lblDuration)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDestCountry)
                                .addGap(18, 18, 18)
                                .addComponent(lblDestCity)
                                .addGap(18, 18, 18)
                                .addComponent(lblDestAirport))
                            .addComponent(lblAircraft)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDepCountry)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCrew, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDepCity)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDepAirport)))))))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAircraft))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDepCountry)
                    .addComponent(lblDepCity)
                    .addComponent(lblDepAirport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDestCountry)
                    .addComponent(lblDestCity)
                    .addComponent(lblDestAirport))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDuration))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTimeFrom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTimeTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPrice))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFlightsActionPerformed
        // TODO add your handling code here:
        GetDetails();
    }//GEN-LAST:event_cmbFlightsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAircraft;
    private javax.swing.JLabel lblCrew;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepAirport;
    private javax.swing.JLabel lblDepCity;
    private javax.swing.JLabel lblDepCountry;
    private javax.swing.JLabel lblDestAirport;
    private javax.swing.JLabel lblDestCity;
    private javax.swing.JLabel lblDestCountry;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTimeFrom;
    private javax.swing.JLabel lblTimeTo;
    // End of variables declaration//GEN-END:variables
}
